name: PR
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ci:
    name: CI
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  merge-pr:
    name: auto-merge
    needs: ci
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - run: pip install requests && python github_actions/auto_merge_pull_requests/merge_pr.py
