name: PR
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  merge-pr:
    name: auto-merge
    needs: ci
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.2.0
        with:
          github-token: ${{github.token}}
          script: |
            let pull = github.pulls.get({owner: context.repo.owner, repo: context.repo.repo, pull_number: context.payload.number});
            console.log(pull);
            github.git.deleteRef({owner: context.repo.owner, repo: context.repo.repo, ref: context});
#            github.pulls.merge({owner: context.repo.owner, repo: context.repo.repo, pull_number: context.payload.number})

