name: PR
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  merge-pr:
    name: auto-merge
    needs: ci
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.2.0
        with:
          github-token: ${{github.token}}
          script: |
            github.pulls.merge({owner: "rcasperson-jc", repo: "actions-test", pull_number: 5})
            github.git.deleteRef({owner: "rcasperson-jc", repo: "actions-test", ref: "branch-name"})
