name: Auto-merge PR
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  build:
    name: Action Test
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - run: pip install requests && python github_actions/auto_merge_pull_requests/merge_pr.py
