name: CI
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: CI
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - run: exit 1