name: Update PR Branches
on:
  pull_request:
    types: [closed]

jobs:
  update-prs:
    name: Update PR Branches
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.2.0
        with:
          github-token: ${{github.token}}
          script: |
            let [owner, repo] = context.payload.repository.full_name.split("/");

            github.pulls.list({owner, repo})
            .then(res => {
              const prs = res.data;
              for (const pr of prs) {
                const pull_number = pr.number;
                console.log(`Updating PR #${pull_number}`);
                github.pulls.updateBranch({owner, repo, pull_number});
              }
            })
