name: Update PR Branches
on:
  push:
    branches:
      - master
      - krypton-daily

jobs:
  update-prs:
    name: Update PR Branches
      runs-on: ubuntu-latest
      steps:
        - uses: actions/github-script@0.2.0
          with:
            github-token: ${{github.token}}
            script: |
              console.log(context)
