name: Update PR Branches
on:
  push:
    branches:
      - master
      - krypton-daily

jobs:
  update-prs:
    name: Update PR Branches
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.2.0
        with:
          github-token: ${{github.token}}
          script: |
            let [owner, repo] = context.payload.repository.full_name.split("/");

            github.pulls.list({owner, repo})
            .then(res => {
              const prs = res.data;
              console.log(prs);
              for (const pr of prs) {
                const pull_number = pr.number;
                console.log(`Updating PR #${pull_number}`);
                github.pulls.updateBranch({owner, repo, pull_number});

                const path = ".tmpfile";
                const message = "Updating a tmpfile to trigger a build

                This is because of https://github.community/t5/GitHub-Actions/Check-Suite-created-by-a-Workflow-doesn-t-complete-even-though/td-p/33390
                ";
                const content = pull_number
                github.repos.createOrUpdateFile({owner, repo, path, message, content})
              }
            })
